# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SocketServer' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for SocketServer
	pod 'CocoaAsyncSocket', '~> 7.6.1'

  target 'SocketServerTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'SocketServerUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
